apiVersion: v1
kind: Service
metadata:
  name: job-portal-backend-service
spec:
  selector:
    app: job-portal-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
